version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: DB_NAME_EXAMPLE
      POSTGRES_USER: USERNAME_EXAMPLE
      POSTGRES_PASSWORD: PASSWORD_EXAMPLE
